Module1 task3
htmlacademy-animation/472965-magic-vacation-1 pull request #3
Opened 2020-10-04 04:58 UTC by victoriaZubareva

2020-10-04 08:17 UTC, abeluzhenko requested changes

2020-10-04 08:17 UTC, abeluzhenko commented on source/scss/blocks/animations.scss
> +  z-index: 5; // 5 т.к. у page-header  z-index: 10
С таким значением z-index оверлей будет полностью перекрывать все, кроме меню. А нам нужно, чтобы он перекрывал только секцию с фоном (.animation-screen). 
Т.е. значение z-index можно не указывать, т.к. оверлей и так выше фона, потому что ниже в DOM-дереве.

2020-10-04 08:17 UTC, abeluzhenko commented on source/scss/blocks/animations.scss
> +  transform: translateY(100%);
В задании условие анимировать именно свойство height, от 0 до 100%. Мне больше нравится ваше решение. Действительно, лучше всегда анимировать свойство transform, т.к. такие анимации не вызывают reflow и работают быстрее.
Но, чтобы достичь нужного эффекта (оверлей, как шторка, которая опускается сверху-вниз), нужно изменить начальное смещение, вместа 100% должно быть -100%

2020-10-04 15:39 UTC, victoriaZubareva commented on source/scss/blocks/animations.scss
> +  transform: translateY(100%);
Спасибо за такие развернутые комментарии!

2020-10-05 13:20 UTC, abeluzhenko approved these changes

2020-10-05 13:21 UTC, merged